### ISSUE TITLE
build a docker image and push it to registry

### ISSUE THREAD

**Issue by TimoKramer** [bob-cd/bob#76]
It should be possible to build a docker image inside bob and push it to a registry because nowadays people deploy with containers and that feature might be crucial.

It should be sufficient to find a way to do that maybe with buildah or something comparable and document that.

**Comment by TimoKramer** [comment]
I know it is hard to build a container with unprivileged tools on centos7

**Comment by lispyclouds** [comment]
Just occured to me, a Docker image is just an artifact and wouldn't it be easier and more semantic to implement this in an artifact store? We build the packaging thing like the jar and upload all the necessary things to the artifact store which builds and pushes the image. That way bob also doesnt have to care about docker auth.

What say @TimoKramer ?

**Comment by TimoKramer** [comment]
That would mean another build system behind Bob? To keep Bob clean we could `save` and `load` the images to a tarball and shovel that to a docker uploader. I would see that tarball as the build artifact.

**Comment by lispyclouds** [comment]
I am thinking something like: https://github.com/bob-cd/artifact-docker

This implements the same interface as an artifact store and the upload here would be the source and image tag and this just builds and pushes(with auth if needed)

My idea is to not allocated too much privileges and complexity to bob, maybe manually creating the tar ball would be bit too verbose?

**Comment by TimoKramer** [comment]
As long as artifact-docker does not become a new Bob I am totally fine. Just wondering if you will have to implement queuing and orchestration again here... because some people build a lot of (complex) images that take time to build. And essentially that is what Bob is about, right?

PS: Bob needs auth anyway to fetch images from private repos, right?

**Comment by lispyclouds** [comment]
> Bob needs auth anyway to fetch images from private repos, right?

For starters, simplicity and the fact that Bob is probably powering a more abstracted system(CI platform) I'm assuming the runners are deployed in VPCs/subnets with network access to private registries. But its a valid concern and we should think about it.

> Just wondering if you will have to implement queuing and orchestration again here

The way that I'm envisioning it for now is this is an orthognal system that purely does builds and pushes and is able to handle concurrent invocations. Its any other server after all. This should not be a `coupled` exectuion from Bob wherein Bob is halted till the possibly complex docker build is done. The hope here is to encourage folks to do more and more orchestration in Bob rather than the Dockerfile. That should only be a `COPY `of the artifact and and `ENTRYPOINT`. For me thats idiomatic docker. Bob already (ab)uses Docker as a build system 😛 

On these thoughts im thinkig is this in the realm of CD more that CI? Should we have another core concept in Bob like `Deployment`? Like we have `Pipeline, Resource and Artifact`? It will have its `Deployer` service too?

Very very hammock, keep the ideas flowing!!

**Comment by TimoKramer** [comment]
alright, with this perspective I get it.

**Comment by lispyclouds** [comment]
Hammock 2:

Since the ability to run docker commands simply needs a `/var/run/docker.sock` to be present and the daemon to be listening on it and since Bob is executing the build in a docker daemon, we can just simply mount Bob's `/var/run/docker.sock` inside the container.

That way the uses who need to run docker commands inside Bob can do so by starting from an image like `docker:stable` and we can expose some config to mount the socket or do it implicitly for every build.

This way the container that Bob has created doesnt need to be `privileged`.

**Comment by lispyclouds** [comment]
Docker commands can now be used in Bob by using an image having a base image having the `docker-cli` installed like `docker:stable` or `docker:latest`. This combined with the fact that the docker socket is mounted into the build container, any docker commands should be successfully executed.

This idiomatically should be used in another downstream pipeline which can consume an artifact from another pipeline as an internal [resource](https://bob-cd.github.io/pages/concepts/resource.html) which tests and build a deployable artifact. The docker image build should be minimal and lean as possible, avoid using complex orchestration in the Docker as Bob does that already 😛
